on: push
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build iOS Action
      uses: lcp29/ios-build-action@master
      with:
        configuration: Release
        export-method: ad-hoc
        scheme: Paperkey
        project-path: Paperkey.xcodeproj
        workspace-path: Paperkey.xcodeproj/project.xcworkspace
        output-path: .
        ios-app-id: com.helmholtz.Paperkey
    - name: Make IPA
      run: mkdir Payload & cp -r ./Build/Products/Release-iphoneos/Paperkey.app ./Payload & zip -r Paperkey.zip Payload & ls & mv Paperkey.zip Paperkey.ipa
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
