on: push
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - name: Build iOS Action
      uses: lcp29/ios-build-action@master
      with:
        configuration: Release
        export-method: ad-hoc
        project-path: ${{GITHUB_WORKSPACE}}/Paperkey.xcodeproj
        output-path: build-${{ github.sha }}.ipa
        team-id: ${{ secrets.TEAM_ID }}
        team-name: ${{ secrets.TEAM_NAME }}
        ios-app-id: com.helmholtz.Paperkey
        apple-key-id: 0
        apple-key-issuer-id: 0
        apple-key-content: 0
